module:
  name: Name of the module
  title: Can be used as meta title
  lang: fr
  hostname: http://example.com
  namespace: Ephect\Modules\DataAccess
  framework: vendor/ephect-io/framework/Ephect
  javascripts: vendor/ephect-io/javascripts/Ajil
